### ISSUE TITLE
[BUG] Running the solution is getting null error in metadata migration

### ISSUE THREAD

**Issue by rudney-souza** [opensearch-project/opensearch-migrations#1177]
### What is the bug?
After running the snapshot command, and waiting till completion, ive ran the command for metadata evaluate and got an null error

### How can one reproduce the bug?
making a snapshot from ES_6.7 and then try to get metadata evaluated

### What is the expected behavior?
A normal migration from ES_6.7 to OS_2.17

### What is your host/environment?
ES_6.7 to OS_2.17

### Do you have any screenshots?
![image](https://github.com/user-attachments/assets/f659b20b-7a03-4487-93c0-9c0b33650e04)
![image](https://github.com/user-attachments/assets/ee1c99d8-c1cb-4862-a92f-bd1d2b9f6a14)
<img width="1171" alt="image" src="https://github.com/user-attachments/assets/5f5feafe-eb75-4ff7-8c85-315ba6b986cf">

**Comment by rudney-souza** [comment]
Thanks for  response @peternied, so i got those logs in here
<img width="1603" alt="image" src="https://github.com/user-attachments/assets/44cb07fb-152e-46b6-a732-06d41bc719e6">
<img width="1593" alt="image" src="https://github.com/user-attachments/assets/0b438883-407c-47cd-a9f5-2ee51e4d4670">
<img width="271" alt="image" src="https://github.com/user-attachments/assets/a799258e-ce3a-4279-bbf9-377d0bc083fd">

**Comment by peternied** [comment]
@rudney-souza Thanks - I'm not seeing any [ERROR] entries or exception call stacks in what you've posted.  Is it possible for you to share with me the full log contents privately?

I'm on the OpenSearch Slack instance as `Peter Nied` which might be a faster and private way to discover the root cause, [see OpenSearch Slack](https://opensearch.org/slack.html).  Alternatively you can email at petern@amazon.com

**Comment by peternied** [comment]
Extracted the full callstack from the log file:
```
2024-12-04 19:55:04,302 ERROR o.o.m.c.Evaluate [main] Unexpected failure
java.lang.NullPointerException: null
        at org.opensearch.migrations.transformation.rules.IndexMappingTypeRemoval.canApply(IndexMappingTypeRemoval.java:56) ~[transformation-0.1.0-SNAPSHOT.jar:?]
        at org.opensearch.migrations.transformation.rules.IndexMappingTypeRemoval.applyTransformation(IndexMappingTypeRemoval.java:73) ~[transformation-0.1.0-SNAPSHOT.jar:?]
        at org.opensearch.migrations.transformation.rules.IndexMappingTypeRemoval.applyTransformation(IndexMappingTypeRemoval.java:40) ~[transformation-0.1.0-SNAPSHOT.jar:?]
        at org.opensearch.migrations.bulkload.transformers.Transformer_ES_6_8_to_OS_2_11.lambda$transformIndex$3(Transformer_ES_6_8_to_OS_2_11.java:78) ~[RFS-0.1.0-SNAPSHOT.jar:?]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at org.opensearch.migrations.bulkload.transformers.Transformer_ES_6_8_to_OS_2_11.transformIndex(Transformer_ES_6_8_to_OS_2_11.java:78) ~[RFS-0.1.0-SNAPSHOT.jar:?]
        at org.opensearch.migrations.bulkload.transformers.Transformer_ES_6_8_to_OS_2_11.lambda$transformGlobalMetadata$1(Transformer_ES_6_8_to_OS_2_11.java:41) ~[RFS-0.1.0-SNAPSHOT.jar:?]
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at org.opensearch.migrations.bulkload.transformers.Transformer_ES_6_8_to_OS_2_11.transformGlobalMetadata(Transformer_ES_6_8_to_OS_2_11.java:38) ~[RFS-0.1.0-SNAPSHOT.jar:?]
        at org.opensearch.migrations.bulkload.transformers.CompositeTransformer.transformGlobalMetadata(CompositeTransformer.java:16) ~[RFS-0.1.0-SNAPSHOT.jar:?]
        at org.opensearch.migrations.bulkload.worker.MetadataRunner.migrateMetadata(MetadataRunner.java:25) ~[RFS-0.1.0-SNAPSHOT.jar:?]
        at org.opensearch.migrations.commands.MigratorEvaluatorBase.migrateGlobalMetadata(MigratorEvaluatorBase.java:115) ~[MetadataMigration-0.1.0-SNAPSHOT.jar:?]
        at org.opensearch.migrations.commands.MigratorEvaluatorBase.migrateAllItems(MigratorEvaluatorBase.java:86) ~[MetadataMigration-0.1.0-SNAPSHOT.jar:?]
        at org.opensearch.migrations.commands.Evaluate.execute(Evaluate.java:29) [MetadataMigration-0.1.0-SNAPSHOT.jar:?]
        at org.opensearch.migrations.MetadataMigration.main(MetadataMigration.java:77) [MetadataMigration-0.1.0-SNAPSHOT.jar:?]
```

**Comment by peternied** [comment]
@rudney-souza I've merged a fix for this issue, you can pick it up immediately by going onto the bootstrap box with the following steps
```bash
cd /opensearch-migrations/deployment/cdk/opensearch-service-migration
git fetch origin
git merge origin/main
./buildDockerImages.sh
# Confirm any cdk.context.json settings and then redeploy
./deploy.sh
```

**Comment by rudney-souza** [comment]
That sounds nice @peternied , thanks a lot!
