### ISSUE TITLE
[BUG] Subnet requirement in a VPC

### ISSUE THREAD

**Issue by vnykmr36** [opensearch-project/opensearch-migrations#502]
### What is the bug?
_When deploying the required resources such as MSK during `cdk deploy` step, deployment fails with subnet requirement during following cases:_

_-> There cannot be subnets spanning more than 3 AZs._
_-> There has to be both Public and Private subnets in a VPC._

### How can one reproduce the bug?
_Simply use a VPC with more AZs and only public subnets or private subnets to deploy the migration tools._

### What is the expected behavior?
_There should be customized behavior of choosing subnets using flags or options to support the deployment._

### What is your host/environment?
_Using CFN launch template from documentation._

### Do you have any screenshots?
_NA_

### Do you have any additional context?

```
Error: Lambda Functions in a public subnet can NOT access the internet. If you are aware of this limitation and would still like to place the function in a public subnet, set `allowPublicSubnet` to true
    at NodejsFunction.configureVpc (/opensearch-migrations/deployment/cdk/opensearch-service-migration/node_modules/aws-cdk-lib/aws-lambda/lib/function.js:1:21161)
    at new Function (/opensearch-migrations/deployment/cdk/opensearch-service-migration/node_modules/aws-cdk-lib/aws-lambda/lib/function.js:1:11323)
    at new NodejsFunction (/opensearch-migrations/deployment/cdk/opensearch-service-migration/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/function.js:1:1669)
    at new MSKUtilityStack (/opensearch-migrations/deployment/cdk/opensearch-service-migration/lib/msk-utility-stack.ts:128:37)
    at new StackComposer (/opensearch-migrations/deployment/cdk/opensearch-service-migration/lib/stack-composer.ts:325:35)
    at Object.<anonymous> (/opensearch-migrations/deployment/cdk/opensearch-service-migration/bin/app.ts:22:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module.m._compile (/opensearch-migrations/deployment/cdk/opensearch-service-migration/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/opensearch-migrations/deployment/cdk/opensearch-service-migration/node_modules/ts-node/src/index.ts:1621:12)
```

**Comment by lewijacn** [comment]
Thanks for the ticket, agree that VPC requirements should be called out in documentation and even better a validation stage in the CDK to call out detected mismatches for a provided VPC. Here is the associated JIRA for tracking: https://opensearch.atlassian.net/browse/MIGRATIONS-1496

**Comment by lewijacn** [comment]
This issue should be resolved with the merging of this PR: https://github.com/opensearch-project/opensearch-migrations/pull/533

We now call out in documentation that the VPC used must have at least two private subnets that span at least two AZs. We have introduced more VPC validations during the synthesis stage to catch these issues earlier, and are also able to handle more than 2 AZs if provided and we need to select a subset.
